name: Build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set tag variable
        id: var
        run: |
          echo ::set-output name=TAG::$(cat Dockerfile | grep -o 'version.*' | cut -f2- -d=)

      - name: Print tag var
        run: |
          echo ${{ steps.var.outputs.TAG }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: wozorio/swiss-army-knife:${{ steps.var.outputs.TAG }}
